// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/buy": {
    params: {};
  };
  "/buyer-presentation": {
    params: {};
  };
  "/property-search": {
    params: {};
  };
  "/saved-properties": {
    params: {};
  };
  "/exchange-support": {
    params: {};
  };
  "/individual-property-page": {
    params: {};
  };
  "/our-agents": {
    params: {};
  };
  "/our-agents2": {
    params: {};
  };
  "/agent-page": {
    params: {};
  };
  "/our-services": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/buy" | "/buyer-presentation" | "/property-search" | "/saved-properties" | "/exchange-support" | "/individual-property-page" | "/our-agents" | "/our-agents2" | "/agent-page" | "/our-services";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/buy.tsx": {
    id: "routes/buy";
    page: "/buy";
  };
  "routes/buyer-presentation.tsx": {
    id: "routes/buyer-presentation";
    page: "/buyer-presentation";
  };
  "routes/property-search.tsx": {
    id: "routes/property-search";
    page: "/property-search";
  };
  "routes/saved-properties.tsx": {
    id: "routes/saved-properties";
    page: "/saved-properties";
  };
  "routes/exchange-support.tsx": {
    id: "routes/exchange-support";
    page: "/exchange-support";
  };
  "routes/individual-property-page.tsx": {
    id: "routes/individual-property-page";
    page: "/individual-property-page";
  };
  "routes/our-agents.tsx": {
    id: "routes/our-agents";
    page: "/our-agents";
  };
  "routes/our-agents2.tsx": {
    id: "routes/our-agents2";
    page: "/our-agents2";
  };
  "routes/agent-page.tsx": {
    id: "routes/agent-page";
    page: "/agent-page";
  };
  "routes/our-services.tsx": {
    id: "routes/our-services";
    page: "/our-services";
  };
};

type RouteModules = {
  "root": typeof import("./non-payloadcms-version/app/root.js");
  "routes/home": typeof import("./non-payloadcms-version/app/routes/home.js");
  "routes/buy": typeof import("./non-payloadcms-version/app/routes/buy.js");
  "routes/buyer-presentation": typeof import("./non-payloadcms-version/app/routes/buyer-presentation.js");
  "routes/property-search": typeof import("./non-payloadcms-version/app/routes/property-search.js");
  "routes/saved-properties": typeof import("./non-payloadcms-version/app/routes/saved-properties.js");
  "routes/exchange-support": typeof import("./non-payloadcms-version/app/routes/exchange-support.js");
  "routes/individual-property-page": typeof import("./non-payloadcms-version/app/routes/individual-property-page.js");
  "routes/our-agents": typeof import("./non-payloadcms-version/app/routes/our-agents.js");
  "routes/our-agents2": typeof import("./non-payloadcms-version/app/routes/our-agents2.js");
  "routes/agent-page": typeof import("./non-payloadcms-version/app/routes/agent-page.js");
  "routes/our-services": typeof import("./non-payloadcms-version/app/routes/our-services.js");
};