/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'css-styles': CssStyle;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'css-styles': CssStylesSelect<false> | CssStylesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * URL slug for this page (e.g., "home", "about")
   */
  slug: string;
  blocks: (
    | {
        variant: 'default' | 'full-width-color' | 'split' | 'agent';
        headingSegments?:
          | {
              text: string;
              /**
               * Hex color code (e.g., #DAE684)
               */
              color?: string | null;
              breakOnMobile?: boolean | null;
              breakOnDesktop?: boolean | null;
              id?: string | null;
            }[]
          | null;
        subheading?: string | null;
        ctaPrimaryLabel?: string | null;
        ctaPrimaryLink?: string | null;
        ctaSecondaryLabel?: string | null;
        ctaSecondaryLink?: string | null;
        /**
         * Background image for hero section
         */
        backgroundImage?: (string | null) | Media;
        /**
         * Agent image (for agent variant)
         */
        agentImage?: (string | null) | Media;
        agentEmail?: string | null;
        agentPhone?: string | null;
        /**
         * LinkedIn profile URL
         */
        agentLinkedin?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        /**
         * Main heading text (use line breaks for multiple lines)
         */
        heading?: string | null;
        subheading?: string | null;
        bulletPoints?:
          | {
              title: string;
              description: string;
              linkText: string;
              linkHref: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Main image displayed on the right side
         */
        image?: (string | null) | Media;
        ctaText?: string | null;
        ctaHref?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'flippedM';
      }
    | {
        /**
         * Select a CSS style to apply to this container (leave empty for no style)
         */
        cssStyle?: (string | null) | CssStyle;
        /**
         * Add one or more blocks to display inside this container
         */
        blocks?:
          | (
              | {
                  variant: 'default' | 'full-width-color' | 'split' | 'agent';
                  headingSegments?:
                    | {
                        text: string;
                        /**
                         * Hex color code (e.g., #DAE684)
                         */
                        color?: string | null;
                        breakOnMobile?: boolean | null;
                        breakOnDesktop?: boolean | null;
                        id?: string | null;
                      }[]
                    | null;
                  subheading?: string | null;
                  ctaPrimaryLabel?: string | null;
                  ctaPrimaryLink?: string | null;
                  ctaSecondaryLabel?: string | null;
                  ctaSecondaryLink?: string | null;
                  /**
                   * Background image for hero section
                   */
                  backgroundImage?: (string | null) | Media;
                  /**
                   * Agent image (for agent variant)
                   */
                  agentImage?: (string | null) | Media;
                  agentEmail?: string | null;
                  agentPhone?: string | null;
                  /**
                   * LinkedIn profile URL
                   */
                  agentLinkedin?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'hero';
                }
              | {
                  /**
                   * Main heading text (use line breaks for multiple lines)
                   */
                  heading?: string | null;
                  subheading?: string | null;
                  bulletPoints?:
                    | {
                        title: string;
                        description: string;
                        linkText: string;
                        linkHref: string;
                        id?: string | null;
                      }[]
                    | null;
                  /**
                   * Main image displayed on the right side
                   */
                  image?: (string | null) | Media;
                  ctaText?: string | null;
                  ctaHref?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'flippedM';
                }
            )[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'container';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "css-styles".
 */
export interface CssStyle {
  id: string;
  /**
   * Display name for this CSS style (e.g., "Sand Gradient")
   */
  name: string;
  /**
   * CSS class name (e.g., "sand-gradient-background")
   */
  cssClass: string;
  /**
   * The CSS code for this style. Include the class selector.
   */
  css: string;
  /**
   * Only active styles will appear in the Container block selector
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'css-styles';
        value: string | CssStyle;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              variant?: T;
              headingSegments?:
                | T
                | {
                    text?: T;
                    color?: T;
                    breakOnMobile?: T;
                    breakOnDesktop?: T;
                    id?: T;
                  };
              subheading?: T;
              ctaPrimaryLabel?: T;
              ctaPrimaryLink?: T;
              ctaSecondaryLabel?: T;
              ctaSecondaryLink?: T;
              backgroundImage?: T;
              agentImage?: T;
              agentEmail?: T;
              agentPhone?: T;
              agentLinkedin?: T;
              id?: T;
              blockName?: T;
            };
        flippedM?:
          | T
          | {
              heading?: T;
              subheading?: T;
              bulletPoints?:
                | T
                | {
                    title?: T;
                    description?: T;
                    linkText?: T;
                    linkHref?: T;
                    id?: T;
                  };
              image?: T;
              ctaText?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        container?:
          | T
          | {
              cssStyle?: T;
              blocks?:
                | T
                | {
                    hero?:
                      | T
                      | {
                          variant?: T;
                          headingSegments?:
                            | T
                            | {
                                text?: T;
                                color?: T;
                                breakOnMobile?: T;
                                breakOnDesktop?: T;
                                id?: T;
                              };
                          subheading?: T;
                          ctaPrimaryLabel?: T;
                          ctaPrimaryLink?: T;
                          ctaSecondaryLabel?: T;
                          ctaSecondaryLink?: T;
                          backgroundImage?: T;
                          agentImage?: T;
                          agentEmail?: T;
                          agentPhone?: T;
                          agentLinkedin?: T;
                          id?: T;
                          blockName?: T;
                        };
                    flippedM?:
                      | T
                      | {
                          heading?: T;
                          subheading?: T;
                          bulletPoints?:
                            | T
                            | {
                                title?: T;
                                description?: T;
                                linkText?: T;
                                linkHref?: T;
                                id?: T;
                              };
                          image?: T;
                          ctaText?: T;
                          ctaHref?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "css-styles_select".
 */
export interface CssStylesSelect<T extends boolean = true> {
  name?: T;
  cssClass?: T;
  css?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}